export enum ServerErrors {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INCORRECT_DATA_FORMAT_OF_SERVER = 'INCORRECT_DATA_FORMAT_OF_SERVER',
  INCORRECT_DATA_FORMAT_OF_CLIENT = 'INCORRECT_DATA_FORMAT_OF_CLIENT',
}
